import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <>This is constant</>
        <a href="/list">Go to list</a>
        <a href="/">Go to home</a>
        {children}
      </body>
    </html>
  );
}
